version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/dcms
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=secret
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
